version: '3'
services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
